trigger:
  branches:
    include:
      - main  # Adjust as needed

pool:
  name: 'Self-Hosted-Agent-Pool'  # Replace with your self-hosted agent pool name

variables:
  pythonVersion: '3.10'  # Specify your Python version (3.7, 3.8, 3.9, or 3.10)

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Inventory Management Application'
  steps:

  - checkout: self

  # Use the specified version of Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  # Verify the installed Python version
  - script: python --version
    displayName: 'Check Python Version'

  # Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Run the application
  - script: |
      python run.py
    displayName: 'Run the application'
    
  # Publish pipeline artifacts
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/app'  # Adjust as necessary
      artifact: 'appArtifact'
      publishLocation: 'pipeline'

  # Deploy to Azure Web App
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure subscription 1 (145b29a3-be32-4c17-ad9c-8f8fb02b04a3)'
      appType: 'webApp'
      WebAppName: 'Inventorydbu'
      package: '$(Pipeline.Workspace)/appArtifact/*.zip'
      enableCustomDeployment: true
