pool:
  name: 'Default'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

# Replace the UsePythonVersion task with the following if skipping
- script: |
    python --version  # Verify Python path is accessible
  displayName: 'Verify Python Version'
