trigger:
  branches:
    include:
      - main  # Adjust to your branch name if different

pool:
  name: 'Default'  # Replace with your self-hosted agent's pool name

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12.7'
        addToPath: true

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install Python dependencies'

    - script: |
        source venv/bin/activate
        pytest
      displayName: 'Run Tests'
      condition: succeeded()

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1 (145b29a3-be32-4c17-ad9c-8f8fb02b04a3)'
        appName: 'Inventorydbu'
        package: $(System.DefaultWorkingDirectory)/app
      displayName: 'Deploy to Azure Web App'
